---
- name: install Vim on CentOS servers
  hosts: dev # dev group from inventory.yaml
  gather_facts: no
  tasks:
    - name: Ping
      when: ansible_distribution_version == "7.8"
      ping:

    - name: Install Vim
      when: ansible_distribution_version == "7.8"
      yum:
        name: vim
        state: latest